alter table public.stg_to_ods_monitoring
add column streamed_by_base_biometric character varying;
alter table public.stg_to_ods_monitoring
add column streamed_by_recapture_biometric character varying;
alter table public.stg_to_ods_monitoring
add column streamed_by_carecardcd4 character varying;
alter table public.stg_to_ods_monitoring
add column streamed_by_cervical_cancer character varying;
alter table public.stg_to_ods_monitoring
add column streamed_by_cryptocol_antigen character varying;
alter table public.stg_to_ods_monitoring
add column streamed_by_tbstatus_tbscreening character varying;
alter table public.stg_to_ods_monitoring
add column streamed_by_client_verification character varying;
alter table public.stg_to_ods_monitoring
add column streamed_by_pharmacy_details_regimen character varying;